#!/usr/bin/env python3
"""
EasySourcing — sample asset-register files for testing the Import Register feature.

Generates (under download/easysourcing-samples/):
  1. sample-asset-register-fresh.xlsx        10 clean rows -> all import
  2. sample-asset-register-fresh.csv         CSV twin of #1 (ERP export style)
  3. sample-asset-register-dedup-check.xlsx  4 rows re-uploaded (skipped) + 2 new (imported)
  4. sample-asset-register-errors.xlsx       3 broken rows (rejected with reasons) + 2 valid

Column headers deliberately use real-world ERP alias names (Particulars, Group,
Brand, Tag, Floor, Holder) to exercise the platform's header auto-mapping.
Location names match the seeded Meridian Manufacturing location tree so the
location linking can be observed (plus one unknown location -> stays unlinked).
"""
import csv
import os
import sys

XLSX_SKILL_DIR = "/home/z/my-project/skills/xlsx"
for sub in [XLSX_SKILL_DIR, os.path.join(XLSX_SKILL_DIR, "templates")]:
    if sub not in sys.path:
        sys.path.insert(0, sub)

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

OUT = "/home/z/my-project/download/easysourcing-samples"
os.makedirs(OUT, exist_ok=True)

# ── Data ──────────────────────────────────────────────────────────────────────
# Tags MRD-TAG-1001..1010 match the barcode PNGs generated by gen_sample_barcodes.py
FRESH_ROWS = [
    # Asset ID, Particulars, Group, Brand, Model No, Serial No, Tag, Floor, Holder
    ["MRD-FA-1001", "CNC Vertical Machining Center", "Production Machinery", "Haas", "VF-4", "HC-2291-MRD", "MRD-TAG-1001", "CNC Hall 1", "S. Kulkarni"],
    ["MRD-FA-1002", "CNC Turning Lathe", "Production Machinery", "Fanuc", "Alpha-T21", "FN-88410", "MRD-TAG-1002", "CNC Hall 2", "S. Kulkarni"],
    ["MRD-FA-1003", "Air Compressor 30kW", "Utilities", "Atlas Copco", "GA-30", "AC-304512", "MRD-TAG-1003", "Workshop", "P. Yadav"],
    ["MRD-FA-1004", "Injection Moulding Machine 120T", "Production Machinery", "Engel", "Duo-120", "EN-120776", "MRD-TAG-1004", "Assembly Line 1", "R. Deshmukh"],
    ["MRD-FA-1005", "Hydraulic Pallet Stacker", "Material Handling", "Godrej", "PS-2030", "GJ-2024-3311", "MRD-TAG-1005", "Raw Material Store", "M. Joshi"],
    ["MRD-FA-1006", "Industrial Storage Racking (Bay 4)", "Storage Infrastructure", "Fami", "FAMI-90B4", "—", "MRD-TAG-1006", "Warehouse Block B", "M. Joshi"],
    ["MRD-FA-1007", "Precision Digital Vernier Caliper Set", "Inspection Equipment", "Mitutoyo", "CD-20APX", "MT-55102", "MRD-TAG-1007", "FG Bay 1", "A. Iyer"],
    ["MRD-FA-1008", "Server Rack 42U with UPS", "IT Equipment", "APC", "SR-42U-10K", "APC-90333", "MRD-TAG-1008", "Server Room", "N. Firodia"],
    ["MRD-FA-1009", "CAD Workstation HP Z8", "IT Equipment", "HP", "Z8-G5", "HPZ8-77421", "MRD-TAG-1009", "Design Studio", "N. Firodia"],
    ["MRD-FA-1010", "Diesel Generator 125 kVA", "Utilities", "Kirloskar", "KG-125AS", "KOEL-12566", "MRD-TAG-1010", "Annex Shed", "P. Yadav"],  # unknown location -> stays unlinked
]

DEDUP_ROWS = [
    # same Asset IDs as FRESH -> duplicates get skipped on re-import
    ["MRD-FA-1001", "CNC Vertical Machining Center", "Production Machinery", "Haas", "VF-4", "HC-2291-MRD", "MRD-TAG-1001", "CNC Hall 1", "S. Kulkarni"],
    ["MRD-FA-1003", "Air Compressor 30kW", "Utilities", "Atlas Copco", "GA-30", "AC-304512", "MRD-TAG-1003", "Workshop", "P. Yadav"],
    ["MRD-FA-1007", "Precision Digital Vernier Caliper Set", "Inspection Equipment", "Mitutoyo", "CD-20APX", "MT-55102", "MRD-TAG-1007", "FG Bay 1", "A. Iyer"],
    ["MRD-FA-1008", "Server Rack 42U with UPS", "IT Equipment", "APC", "SR-42U-10K", "APC-90333", "MRD-TAG-1008", "Server Room", "N. Firodia"],
    # new rows -> import
    ["MRD-FA-1011", "Bench Grinding Machine", "Production Machinery", "Bosch", "GBG-60-20", "BSH-66120", "MRD-TAG-1011", "Workshop", "P. Yadav"],
    ["MRD-FA-1012", "Wi-Fi Access Points (6 units)", "IT Equipment", "Ubiquiti", "U6-Pro", "UBI-2024-088", "MRD-TAG-1012", "3rd Floor", "N. Firodia"],
]

ERROR_ROWS = [
    # 3 broken rows (rejected with reasons) + 2 valid rows (imported)
    ["MRD-BAD-201", "", "Production Machinery", "Haas", "VF-2", "HC-11003", "MRD-TAG-2001", "CNC Hall 1", "S. Kulkarni"],        # missing description
    ["MRD-BAD-202", "Welding Station", "", "Miller", "XMT-450", "MLR-91220", "MRD-TAG-2002", "Workshop", "P. Yadav"],             # missing category
    ["", "Mobile Crane 5T", "Material Handling", "Tata", "LPK-510", "TT-33019", "MRD-TAG-2003", "Warehouse Block B", "M. Joshi"], # missing asset id
    ["MRD-FA-1013", "Paint Booth with Filter Bank", "Production Machinery", "Deccan", "PB-920", "DCN-44190", "MRD-TAG-1013", "Assembly Line 1", "R. Deshmukh"],
    ["MRD-FA-1014", "Forklift Battery Charger", "Utilities", "Exide", "XC-48/100", "EXD-21887", "MRD-TAG-1014", "Raw Material Store", "M. Joshi"],
]

HEADERS = ["Asset ID", "Particulars", "Group", "Brand", "Model No", "Serial No", "Tag", "Floor", "Holder"]
COL_WIDTHS = [13, 34, 22, 12, 12, 15, 15, 20, 13]

# ── Styling helpers (tokens from the skill's base.py) ────────────────────────
HEADER_FILL = PatternFill("solid", fgColor="1B7D46")   # ACCENT_POSITIVE (deep green)
HEADER_FONT = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
DATA_FONT = Font(name="Calibri", size=11, color="1F2937")
TITLE_FONT = Font(name="Calibri", bold=True, size=13, color="111827")
NOTE_FONT = Font(name="Calibri", italic=True, size=10, color="6B7280")
THIN = Side(style="thin", color="D1D5DB")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
CENTER = Alignment(horizontal="center", vertical="center")
LEFT = Alignment(horizontal="left", vertical="center")


def build_sheet(ws, title, rows):
    ws.sheet_view.showGridLines = False
    # B2 canvas origin (skill layout convention)
    ws["B2"] = title
    ws["B2"].font = TITLE_FONT
    ws["B3"] = "Meridian Manufacturing Pvt Ltd — fixed asset register (ERP export)"
    ws["B3"].font = NOTE_FONT

    header_row = 5
    for col, h in enumerate(HEADERS, 2):
        c = ws.cell(row=header_row, column=col, value=h)
        c.fill = HEADER_FILL
        c.font = HEADER_FONT
        c.alignment = CENTER
        c.border = BORDER
    for i, w in enumerate(COL_WIDTHS, 2):
        ws.column_dimensions[get_column_letter(i)].width = w

    for r, row in enumerate(rows, header_row + 1):
        for c, val in enumerate(row, 2):
            cell = ws.cell(row=r, column=c, value=val)
            cell.font = DATA_FONT
            cell.border = BORDER
            cell.alignment = LEFT

    ws.freeze_panes = f"B{header_row + 1}"
    ws.row_dimensions[2].height = 22
    return header_row + len(rows)


def save_xlsx(path, title, rows):
    wb = Workbook()
    ws = wb.active
    ws.title = "Asset Register"
    last = build_sheet(ws, title, rows)
    wb.properties.creator = "Z.ai"
    wb.save(path)
    print(f"ok  {os.path.basename(path)}  ({len(rows)} rows)")
    return last


# 1 ── fresh register xlsx
save_xlsx(os.path.join(OUT, "sample-asset-register-fresh.xlsx"),
          "Asset Register — Fresh Import (10 assets)", FRESH_ROWS)

# 2 ── CSV twin (plain ERP export style)
csv_path = os.path.join(OUT, "sample-asset-register-fresh.csv")
with open(csv_path, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(HEADERS)
    w.writerows(FRESH_ROWS)
print(f"ok  {os.path.basename(csv_path)}  ({len(FRESH_ROWS)} rows)")

# 3 ── dedup-check xlsx
save_xlsx(os.path.join(OUT, "sample-asset-register-dedup-check.xlsx"),
          "Asset Register — Re-upload After ERP Sync (4 duplicates + 2 new)", DEDUP_ROWS)

# 4 ── error-set xlsx
save_xlsx(os.path.join(OUT, "sample-asset-register-errors.xlsx"),
          "Asset Register — Dirty Extract (3 broken + 2 valid rows)", ERROR_ROWS)

print("\nexpected results when imported against Meridian Manufacturing:")
print("  fresh.xlsx        -> imported 10  · duplicates 0 · rejected 0   (Annex Shed stays unlinked)")
print("  dedup-check.xlsx  -> imported 2   · duplicates 4 · rejected 0")
print("  errors.xlsx       -> imported 2   · duplicates 0 · rejected 3")
